services:
  k-bot:
    build:
      context: ./
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    # env_file: ./.env  # Uncomment if .env file exists
networks:
  default:
    driver: bridge
